apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: doomed-apt
resources:
  - deployment.yaml
  - service-nodeport.yaml
  - mysql.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
images:
  - name: mmmmnl/lobotomy
    newTag: v.1.0