apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: doomed-apt
resources:
  - deployment.yaml
  - service-nodeport.yaml
  - mysql.yaml
  - persistent-volume-claim.yaml
  - service-account.yaml
  - backend-config.yaml
  - mysql-pvc.yaml
  - backend-pod-monitoring.yaml
  - otel-collector-deployment.yaml
  - otel-collector-service.yaml
  - otel-collector-config.yaml
images:
  - name: mmmmnl/lobotomycorp
    newTag: v.1.1
