apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-ksa
  namespace: doomed-apt
  annotations:
    iam.gke.io/gcp-service-account: backend-802@doomapt-project.iam.gserviceaccount.com
  labels:
    app: backend
