name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GKE_CLUSTER: doomapt-project-cluster
  GKE_ZONE: asia-southeast1-a

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --file Dockerfile -t mmmmnl/lobotomycorp:latest .
    - name: login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push docker
      run: docker push mmmmnl/lobotomycorp:latest
    - name: üîç DEBUG Print Repo Name
      run: |
        echo "GITHUB REPOSITORY NAME (Case-Sensitive): ${{ github.repository }}"
        echo "GITHUB ACTOR (User/Org): ${{ github.repository_owner }}"
        # ‡∏™‡∏±‡πà‡∏á‡πÉ‡∏´‡πâ Workflow ‡∏•‡πâ‡∏°‡πÄ‡∏´‡∏•‡∏ß‡∏ó‡∏µ‡πà‡∏ô‡∏µ‡πà‡∏ä‡∏±‡πà‡∏ß‡∏Ñ‡∏£‡∏≤‡∏ß ‡πÄ‡∏û‡∏∑‡πà‡∏≠‡∏ï‡∏£‡∏ß‡∏à‡∏™‡∏≠‡∏ö Log ‡∏Å‡πà‡∏≠‡∏ô
        exit 1
    - name: üîê Authenticate to GCP (WIF)
      uses: google-github-actions/auth@v2
      with:
        # ‡∏î‡∏∂‡∏á‡∏Ñ‡πà‡∏≤‡∏à‡∏≤‡∏Å GitHub Secrets
        workload_identity_provider: ${{ secrets.WIF_PROVIDER_ID }}
        service_account: ${{ secrets.SA_EMAIL }}
        # Project ID ‡∏Å‡πá‡∏™‡∏≤‡∏°‡∏≤‡∏£‡∏ñ‡∏î‡∏∂‡∏á‡∏à‡∏≤‡∏Å Secret ‡πÑ‡∏î‡πâ‡πÄ‡∏ä‡πà‡∏ô‡∏Å‡∏±‡∏ô
        project_id: ${{ secrets.GCP_PROJECT_ID }} 
    - name: ‚öôÔ∏è Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
