name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GKE_CLUSTER: doomapt-project-cluster
  GKE_ZONE: asia-southeast1-a

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --file Dockerfile -t mmmmnl/lobotomycorp:latest .
    - name: login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push docker
      run: docker push mmmmnl/lobotomycorp:latest

    # - name: üîê Authenticate to GCP (WIF)
    #   uses: google-github-actions/auth@v2
    #   with:
    #     credentials_json: ${{ secrets.GCP_SA_KEY }}
    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
    # - name: ‚öôÔ∏è Get GKE Credentials
    #   uses: google-github-actions/get-gke-credentials@v2
    #   with:
    #     cluster_name: ${{ env.GKE_CLUSTER }}
    #     location: ${{ env.GKE_ZONE }}
    #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      
    # - name: Install Kustomize
    #   run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        
    # - name: üìù Update K8s Image Tag
    #   run: |
    #     cd k8s
    #     ../kustomize edit set image mmmmnl/lobotomycorp:${{ github.sha }}
          
    # - name: üöÄ Deploy Backend to GKE
    #   run: |
    #     kubectl apply -k k8s --namespace=doomed-apt
          
    # - name: ‚è≥ Wait for Deployment Rollout
    #   run: kubectl rollout status deployment/backend-deployment --namespace=doomed-apt --timeout=5m
