name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GKE_CLUSTER: doomapt-project-cluster
  GKE_ZONE: asia-southeast1

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --file Dockerfile -t mmmmnl/lobotomycorp:latest .
    - name: login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push docker
      run: docker push mmmmnl/lobotomycorp:latest
    - name: üîç DEBUG Print Repo Name
      run: |
        echo "GITHUB REPOSITORY NAME (Case-Sensitive): ${{ github.repository }}"
        echo "GITHUB ACTOR (User/Org): ${{ github.repository_owner }}"
    - name: üîê Authenticate to GCP (WIF)
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    - name: ‚öôÔ∏è Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

- name: Install Kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        
      - name: üìù Update K8s Image Tag
        run: |
          K8S_PATH="k8s"
          # üö® 1. ‡πÄ‡∏õ‡∏•‡∏µ‡πà‡∏¢‡∏ô Directory ‡πÑ‡∏õ‡∏ó‡∏µ‡πà‡πÇ‡∏ü‡∏•‡πÄ‡∏î‡∏≠‡∏£‡πå K8s
          cd $K8S_PATH
          # 2. ‡πÄ‡∏£‡∏µ‡∏¢‡∏Å Kustomize Binary ‡∏à‡∏≤‡∏Å Root Directory (‡∏≠‡∏¢‡∏π‡πà‡πÄ‡∏´‡∏ô‡∏∑‡∏≠‡∏Ç‡∏∂‡πâ‡∏ô‡πÑ‡∏õ 1 ‡∏Ç‡∏±‡πâ‡∏ô)
          ../kustomize edit set image mmmmnl/lobotomycorp:${{ github.sha }}
          
      - name: üöÄ Deploy Backend and MySQL
        run: |
          K8S_PATH="k8s"
          # 3. Deploy ‡∏à‡∏≤‡∏Å Root ‡πÇ‡∏î‡∏¢‡∏£‡∏∞‡∏ö‡∏∏ Path K8S
          kubectl apply -k $K8S_PATH --namespace=doomed-apt
          
      - name: ‚è≥ Wait for Deployment Rollout
        run: kubectl rollout status deployment/backend-deployment --namespace=doomed-apt --timeout=5m
      
      - name: Install Kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        
      - name: üìù Update K8s Image Tag
        run: |
          K8S_PATH="k8s"
          cd $K8S_PATH 
          ../kustomize edit set image mmmmnl/lobotomy_but_front:${{ github.sha }}
          
      - name: üöÄ Deploy Frontend to GKE
        run: |
          K8S_PATH="k8s/"
          kubectl apply -k $K8S_PATH --namespace=doomed-apt
          
      - name: ‚è≥ Wait for Deployment Rollout
        run: kubectl rollout status deployment/frontend-deployment --namespace=doomed-apt --timeout=5m
