name: 'ğŸš€ Deploy Backend to GKE'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GKE_CLUSTER: doomapt-project-cluster
  GKE_ZONE: asia-southeast1
  IMAGE_NAME: mmmmnl/lobotomycorp

jobs:

  build-and-deploy: 

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: 'ğŸ“¥ Check out code'
      uses: actions/checkout@v4
      
    - name: 'ğŸ³ Build the Docker image'
      run: docker build --file Dockerfile -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: 'ğŸ”‘ Docker Hub Login'
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: 'ğŸ“¤ Push Docker Image'
      run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: 'ğŸ” Authenticate to GCP (WIF)'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    - name: 'âš™ï¸ Get GKE Credentials'
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
      
    - name: 'ğŸ”§ Install Kustomize'
      run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      
    - name: 'ğŸ“ Update K8s Image Tag'
      run: |
        cd k8s
        ../kustomize edit set image mmmmnl/lobotomycorp:${{ github.sha }}
        
    - name: 'ğŸš€ Deploy Backend to GKE'
      run: |
        kubectl apply -k k8s --namespace=doomed-apt
        
    - name: 'â³ Wait for Deployment Rollout'
      run: kubectl rollout status deployment/backend-deployment --namespace=doomed-apt --timeout=5m